# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00d651e0750f07dddac274347daf78cb29b37075049be39a65b1d7a3b8cebb42133336a4ae184bacdabbe48f2eb9cf7d1b2d3a0ec08e052f03df62b630cafc8f

test:
  secret_key_base: b49a2e06a4c0c9aea17e8f53e153e7530992657c654c556903defe08f91810d4052fd4c0334e421e80eaa86a50fbcb1bd0d49e4adaf3c57e87a6dbb586e4b8b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
